import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  resultRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  markerName: {
    fontSize: 10,
    flex: 2,
  },
  value: {
    fontSize: 10,
    flex: 1,
    textAlign: 'center',
  },
  target: {
    fontSize: 10,
    flex: 1,
    textAlign: 'center',
    color: '#666',
  },
  evaluation: {
    fontSize: 10,
    flex: 1,
    textAlign: 'right',
  },
  normal: {
    color: '#22c55e',
  },
  low: {
    color: '#3b82f6',
  },
  moderate: {
    color: '#eab308',
  },
  high: {
    color: '#ef4444',
  },
  ominousAlert: {
    backgroundColor: '#fef2f2',
    padding: 10,
    marginBottom: 15,
    borderRadius: 4,
  },
  ominousText: {
    fontSize: 12,
    color: '#b91c1c',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 8,
    color: '#999',
  },
});

interface LabResultData {
  patientName: string;
  testDate: string;
  ominousCount: number;
  ominousMarkers: string[];
  results: {
    markerName: string;
    categoryName: string;
    value: number;
    unit: string;
    targetRange: string;
    evaluation: string | null;
    deltaFromTarget: number | null;
  }[];
}

interface LabResultPdfProps {
  data: LabResultData;
}

export function LabResultPdf({ data }: LabResultPdfProps) {
  // Group results by category
  const resultsByCategory = data.results.reduce(
    (acc, result) => {
      if (!acc[result.categoryName]) {
        acc[result.categoryName] = [];
      }
      acc[result.categoryName].push(result);
      return acc;
    },
    {} as Record<string, typeof data.results>
  );

  const getEvaluationStyle = (evaluation: string | null) => {
    switch (evaluation) {
      case 'normal':
        return styles.normal;
      case 'low':
        return styles.low;
      case 'moderate':
        return styles.moderate;
      case 'high':
        return styles.high;
      default:
        return {};
    }
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Lab Results Report</Text>
          <Text style={styles.subtitle}>
            Patient: {data.patientName} | Date: {data.testDate}
          </Text>
        </View>

        {data.ominousCount >= 3 && (
          <View style={styles.ominousAlert}>
            <Text style={styles.ominousText}>
              Warning: {data.ominousCount} ominous markers detected
            </Text>
          </View>
        )}

        {Object.entries(resultsByCategory).map(([category, results]) => (
          <View key={category} style={styles.section}>
            <Text style={styles.sectionTitle}>{category}</Text>
            {results.map((result, index) => (
              <View key={index} style={styles.resultRow}>
                <Text style={styles.markerName}>{result.markerName}</Text>
                <Text style={styles.value}>
                  {result.value} {result.unit}
                </Text>
                <Text style={styles.target}>{result.targetRange}</Text>
                <Text style={[styles.evaluation, getEvaluationStyle(result.evaluation)]}>
                  {result.evaluation || '-'}
                </Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Clinic Copilot | {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}
