// Shared marker aliases for fuzzy matching between Vision API output names
// and the internal labMarkers database. Used by both parse-pdf route and vision-extractor.

export const MARKER_ALIASES: Record<string, string[]> = {
  'NT-proBNP': ['NT-proBNP', 'NT proBNP', 'BNP', 'Pro-BNP'],
  CRP: ['CRP', 'C-Reactive Protein', 'C Reactive Protein', 'hs-CRP', 'hsCRP'],
  Homocysteine: ['Homocysteine', 'HCY'],
  'Uric Acid': ['Uric Acid', 'Urate'],
  Iron: ['Iron', 'Serum Iron', 'Fe'],
  UIBC: ['UIBC', 'Unsaturated Iron Binding Capacity'],
  TIBC: ['TIBC', 'Total Iron Binding Capacity'],
  Transferrin: ['Transferrin', 'TRF'],
  'Transferrin Saturation': ['Transferrin Sat', 'Transferrin Saturation', 'TSAT', 'Iron Saturation'],
  'Vitamin B12': ['B12', 'Vitamin B12', 'Cobalamin', 'B-12'],
  Folate: ['Folate', 'Folic Acid', 'Serum Folate'],
  Ferritin: ['Ferritin', 'Serum Ferritin'],
  'Total Cholesterol': ['Total Cholesterol', 'Cholesterol', 'TC', 'Cholesterol, Total'],
  Triglycerides: ['Triglycerides', 'TG', 'Trigs'],
  HDL: ['HDL', 'HDL Cholesterol', 'HDL-C', 'High Density Lipoprotein'],
  LDL: ['LDL', 'LDL Cholesterol', 'LDL-C', 'Low Density Lipoprotein'],
  sdLDL: ['sdLDL', 'Small Dense LDL', 'sd-LDL'],
  'Apo A-1': ['Apo A-1', 'Apolipoprotein A-1', 'Apo-A1', 'ApoA1'],
  'Apo B': ['Apo B', 'Apolipoprotein B', 'ApoB', 'Apo-B'],
  'Lp(a)': ['Lp(a)', 'Lipoprotein(a)', 'Lipoprotein a', 'LPa'],
  Glucose: ['Glucose', 'Blood Glucose', 'Fasting Glucose', 'FBG'],
  Insulin: ['Insulin', 'Fasting Insulin', 'Serum Insulin'],
  HbA1C: ['HbA1c', 'A1C', 'Hemoglobin A1c', 'Glycated Hemoglobin', 'A1c'],
  Calcium: ['Calcium', 'Ca', 'Serum Calcium', 'Total Calcium'],
  Albumin: ['Albumin', 'Serum Albumin', 'ALB'],
  PTH: ['PTH', 'Parathyroid Hormone', 'Intact PTH', 'iPTH'],
  'Vitamin D': ['Vitamin D', 'Vit D', '25-OH Vitamin D', '25-Hydroxy Vitamin D', '25(OH)D'],
  Magnesium: ['Magnesium', 'Mg', 'Serum Magnesium'],
  Sodium: ['Sodium', 'Na'],
  Potassium: ['Potassium', 'K'],
  Chloride: ['Chloride', 'Cl'],
  CO2: ['CO2', 'Carbon Dioxide', 'Bicarbonate', 'HCO3'],
  BUN: ['BUN', 'Blood Urea Nitrogen', 'Urea Nitrogen'],
  'Total Protein': ['Total Protein', 'Protein, Total', 'Serum Protein'],
  Creatinine: ['Creatinine', 'Serum Creatinine', 'Cr'],
  'Cystatin C': ['Cystatin C', 'Cys-C'],
  eGFR: ['eGFR', 'GFR', 'Estimated GFR', 'Glomerular Filtration Rate'],
  ALT: ['ALT', 'SGPT', 'Alanine Aminotransferase'],
  AST: ['AST', 'SGOT', 'Aspartate Aminotransferase'],
  GGT: ['GGT', 'Gamma GT', 'Gamma-Glutamyl Transferase'],
  'Alkaline Phosphatase': ['Alk Phos', 'Alkaline Phosphatase', 'ALP'],
  'Total Bilirubin': ['Total Bilirubin', 'Bilirubin, Total', 'T-Bili', 'TBIL'],
  'Direct Bilirubin': ['Direct Bilirubin', 'Bilirubin, Direct', 'D-Bili', 'DBIL'],
  TSH: ['TSH', 'Thyroid Stimulating Hormone'],
  'T4 Total': ['T4', 'T4 Total', 'Total T4', 'Thyroxine'],
  'T4 Free': ['Free T4', 'FT4', 'T4 Free'],
  'T3 Total': ['T3', 'T3 Total', 'Total T3', 'Triiodothyronine'],
  'T3 Free': ['Free T3', 'FT3', 'T3 Free'],
  WBC: ['WBC', 'White Blood Cell', 'White Blood Cells', 'Leukocytes'],
  RBC: ['RBC', 'Red Blood Cell', 'Red Blood Cells', 'Erythrocytes'],
  Hemoglobin: ['Hemoglobin', 'Hgb', 'Hb'],
  Hematocrit: ['Hematocrit', 'Hct', 'HCT'],
  MCV: ['MCV', 'Mean Corpuscular Volume'],
  MCH: ['MCH', 'Mean Corpuscular Hemoglobin'],
  MCHC: ['MCHC', 'Mean Corpuscular Hemoglobin Concentration'],
  RDW: ['RDW', 'Red Cell Distribution Width', 'RDW-CV'],
  Platelets: ['Platelets', 'PLT', 'Platelet Count', 'Thrombocytes'],
  Neutrophils: ['Neutrophils', 'Neut', 'Neutrophil', 'ANC'],
  Lymphocytes: ['Lymphocytes', 'Lymph', 'Lymphocyte'],
  Monocytes: ['Monocytes', 'Mono', 'Monocyte'],
  Eosinophils: ['Eosinophils', 'Eos', 'Eosinophil'],
  Basophils: ['Basophils', 'Baso', 'Basophil'],
  Estradiol: ['Estradiol', 'E2', 'Estrogen'],
  FSH: ['FSH', 'Follicle Stimulating Hormone'],
  'DHEA-S': ['DHEA-S', 'DHEA Sulfate', 'DHEAS'],
  LH: ['LH', 'Luteinizing Hormone'],
  SHBG: ['SHBG', 'Sex Hormone Binding Globulin'],
  Testosterone: ['Testosterone', 'Total Testosterone'],
  Progesterone: ['Progesterone', 'P4'],
  Globulin: ['Globulin', 'Total Globulin', 'Serum Globulin'],
}
